// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'introduccion',
    'arquitectura',
    'instalacion',
    {
      type: 'category',
      label: 'Frontend',
      items: ['frontend/overview', 'frontend/estructura', 'frontend/estado', 'frontend/autenticacion', ],
    },
    {
      type: 'category',
      label: 'Backend',
      items: ['backend/overview', 'backend/api', 'backend/autenticacion', 'backend/base-de-datos'],
    },
    {
      type: 'category',
      label: 'Componentes',
      items: [
        'frontend/components/layout/intro',  // Enlaza a Button.md
        'frontend/components/sauc0017/intro',  // Enlaza a sauc0017.md

      ],
    },
    'despliegue',
  ],
};

export default sidebars;
