// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Instalación',
      items: ['instalacion/requisitos','instalacion/instalacion','instalacion/despliegue'], 
    },
    {
      type: 'category',
      label: 'Arquitectura',
      items: [
        'arquitectura/overview','arquitectura/frontend','arquitectura/backend','arquitectura/database'   // Enlaza a Button.md

      ],
    },
    {
      type: 'category',
      label: 'Api',
      items: [
        'api/auth',  // Enlaza a Button.md
        'api/endpoints',  // Enlaza a sauc0017.md
        'api/erros',  // Enlaza a sauc0017.md

      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/setup',  // Enlaza a Button.md
        'development/coding-style',  // Enlaza a Button.md
        'development/contributing',  // Enlaza a Button.md

      ],
    },
  ],
};

export default sidebars;
